import { describe, expect, it } from "vitest";
import { computePlanEconomics } from "@/lib/pricing-engine/planEconomics";
import { toEngineAssumptions } from "@/lib/pricing-engine/transforms";
import type { PlanInput } from "@/lib/pricing-engine/types";

/**
 * Ground-truth values generated by running the ORIGINAL Python pricing loop
 * (dash_studio_v4.py's run_model per-plan logic) against its own DEF/DEF_PLANS
 * defaults — see the scratch script used to produce these. This proves the
 * TypeScript port reproduces the source of truth, not just internal consistency.
 */
const DEF_ASSUMPTIONS = toEngineAssumptions({
  genUnitsPerKwDay: 4.5,
  promisedUnitsPerKwDay: 4.0,
  degradationPct: 1.0,
  stepEveryYears: 5,
  userStepPct: 10.0,
  onboardingFeePct: 1.0,
  maxYears: 15,
});

const DEF_PLANS: PlanInput[] = [
  { code: "GROWTH_15", name: "Growth-15", tenureYears: 15, creditRatePerUnit: 4.0, targetXirrPct: 11.5, refundPct: 0 },
  { code: "FLEXI_10", name: "Flexi-10", tenureYears: 10, creditRatePerUnit: 4.5, targetXirrPct: 11.0, refundPct: 0 },
  { code: "SHORT_3", name: "Short-3", tenureYears: 3, creditRatePerUnit: 7.0, targetXirrPct: 10.0, refundPct: 0, autoResell: true },
  { code: "ASSURED_15", name: "Assured-15", tenureYears: 15, creditRatePerUnit: 3.4, targetXirrPct: 10.5, refundPct: 100 },
];

const PYTHON_FIXTURES: Record<string, { fee: number; xirr: number; creditYear1: number; creditYearTen: number }> = {
  GROWTH_15: { fee: 41363.73892216446, xirr: 11.3205809331414, creditYear1: 5840.0, creditYearTen: 6138.905411350709 },
  FLEXI_10: { fee: 38657.68115557856, xirr: 10.765047888765611, creditYear1: 6570.0, creditYearTen: 6601.9891475642735 },
  SHORT_3: { fee: 25178.363636363632, xirr: 9.434808642340887, creditYear1: 10220.0, creditYearTen: 10016.622 },
  ASSURED_15: { fee: 47906.97138029202, xirr: 10.367208057406485, creditYear1: 4964.0, creditYearTen: 5218.069599648103 },
};

describe("computePlanEconomics — regression vs. Python source", () => {
  for (const plan of DEF_PLANS) {
    it(`matches Python fee/XIRR/credit-stream for ${plan.name}`, () => {
      const result = computePlanEconomics(plan, DEF_ASSUMPTIONS);
      const fixture = PYTHON_FIXTURES[plan.code];

      expect(result.feePerKW).toBeCloseTo(fixture.fee, 4);
      expect(result.realizedXirrPct).toBeCloseTo(fixture.xirr, 4);
      expect(result.creditStream[1]).toBeCloseTo(fixture.creditYear1, 6);
      expect(result.creditStream[result.tenureYears]).toBeCloseTo(fixture.creditYearTen, 6);
    });
  }

  it("Growth-15 realized XIRR is close to but slightly below its 11.5% target (onboarding fee drag)", () => {
    const result = computePlanEconomics(DEF_PLANS[0], DEF_ASSUMPTIONS);
    expect(result.realizedXirrPct).toBeLessThan(11.5);
    expect(result.realizedXirrPct).toBeGreaterThan(11.0);
  });

  it("Assured-15's full refund is reflected in the final year's cashflow via a higher fee", () => {
    const withRefund = computePlanEconomics(DEF_PLANS[3], DEF_ASSUMPTIONS);
    const withoutRefund = computePlanEconomics(
      { ...DEF_PLANS[3], refundPct: 0 },
      DEF_ASSUMPTIONS,
    );
    expect(withRefund.feePerKW).toBeGreaterThan(withoutRefund.feePerKW);
  });
});
