import { describe, expect, it } from "vitest";
import { solvePriceTarget } from "@/lib/pricing-engine/internal/priceTargetSolver";

/**
 * Ground-truth fixtures generated by running the ORIGINAL Python Price Target
 * Solver tab logic (dash_studio_v6.py:1050-1086) directly, using the same
 * DEF-style assumptions (units=4.0, deg=1%, step_every=5, host_step=10%,
 * mirror=True, onb=1%).
 */
const ASSUMPTIONS = {
  promisedUnitsPerKwDay: 4.0,
  degradationPct: 0.01,
  stepEveryYears: 5,
  mirrorUserStep: true,
  hostStepPct: 0.1,
  userStepPct: 0.1,
  onboardingFeePct: 0.01,
};

describe("solvePriceTarget — regression vs. Python source", () => {
  it("solves credit rate for ₹50/W, 15y, beat 10.49% XIRR, no refund", () => {
    const result = solvePriceTarget(
      { sellPricePerWatt: 50, tenureYears: 15, targetXirrPct: 10.49, refundPct: 0 },
      ASSUMPTIONS,
    );
    expect(result.creditRatePerUnit).toBeCloseTo(4.613864212963456, 4);
    expect(result.achievedXirrPct).toBeCloseTo(10.490000000000133, 3);
    expect(result.marginVsReferenceCostPerKw).toBeCloseTo(10000.0, 3);
  });

  it("solves credit rate for ₹46/W, 10y, beat 11.0% XIRR, 20% refund", () => {
    const result = solvePriceTarget(
      { sellPricePerWatt: 46, tenureYears: 10, targetXirrPct: 11.0, refundPct: 20 },
      ASSUMPTIONS,
    );
    expect(result.creditRatePerUnit).toBeCloseTo(5.031071620566433, 4);
    expect(result.achievedXirrPct).toBeCloseTo(10.999999999999998, 3);
    expect(result.marginVsReferenceCostPerKw).toBeCloseTo(6000.0, 3);
  });

  it("credit stream has one entry per tenure year, stepping up every stepEveryYears", () => {
    const result = solvePriceTarget(
      { sellPricePerWatt: 50, tenureYears: 15, targetXirrPct: 10.49, refundPct: 0 },
      ASSUMPTIONS,
    );
    expect(result.creditStream).toHaveLength(15);
    // Year 6 should reflect one step-up (10%) vs year 1, modulo degradation.
    const y1 = result.creditStream[0];
    const y6 = result.creditStream[5];
    const impliedStepRatio = y6 / y1 / Math.pow(1 - ASSUMPTIONS.degradationPct, 5);
    expect(impliedStepRatio).toBeCloseTo(1.1, 6);
  });
});
