import { describe, expect, it } from "vitest";
import { runModel } from "@/lib/pricing-engine/internal/runModel";
import type { RunModelAssumptions, RunModelPlanInput } from "@/lib/pricing-engine/types";

/**
 * Ground-truth fixtures generated by running the ORIGINAL Python `run_model()`
 * (dash_studio_v6.py:37-211) against its own DEF/DEF_PLANS defaults — see the
 * scratch script used to produce these (a faithful extraction of just the
 * engine functions, no Dash/openpyxl dependencies). This proves the
 * TypeScript port reproduces the source of truth bit-for-bit (within FP
 * tolerance), not just internal self-consistency.
 */
const DEF_ASSUMPTIONS: RunModelAssumptions = {
  kw: 250,
  capexPerWatt: 40.0,
  genUnitsPerKwDay: 4.5,
  promisedUnitsPerKwDay: 4.0,
  degradationPct: 0.01,
  hostTariffPerUnit: 5.5,
  stepEveryYears: 5,
  hostStepPct: 0.1,
  mirrorUserStep: true,
  userStepPct: 0.1,
  omPerKwYear: 500,
  omEscalationPct: 0.04,
  insurancePerKwYear: 150,
  platformOpexPerKwYear: 300,
  marketingPct: 0.04,
  onboardingFeePct: 0.01,
  sellOutMonths: 6,
  depositMonths: 12,
  ltvPct: 0,
  debtRatePct: 0.1,
  debtTenorYears: 10,
  fdRatePct: 0.072,
  taxRatePct: 0.25,
  discountRatePct: 0.12,
  equityAtT0: 10500000,
  carveOut: true,
  projectType: "new",
  years: 15,
  legacyPremiumPct: 0.05,
  financingType: "equity",
  profitShareSplitUsPct: 0.6,
  profitShareDiminishing: false,
  profitShareBuyoutYears: 7,
};

const DEF_PLANS: RunModelPlanInput[] = [
  { plan: "Growth-15", tenure: 15, credit: 4.0, target: 11.5, refund: 0, mix: 50, resell: false },
  { plan: "Flexi-10", tenure: 10, credit: 4.5, target: 11.0, refund: 0, mix: 25, resell: false },
  { plan: "Short-3", tenure: 3, credit: 7.0, target: 10.0, refund: 0, mix: 15, resell: true },
  { plan: "Assured-15", tenure: 15, credit: 3.4, target: 10.5, refund: 100, mix: 10, resell: false },
];

describe("runModel — equity scenario, regression vs. Python source", () => {
  const { rows, plans, summary } = runModel(DEF_ASSUMPTIONS, DEF_PLANS);

  it("capex matches kw * capex_w * 1000", () => {
    expect(summary.capex).toBeCloseTo(10_000_000, 4);
  });

  it("summary KPIs match the Python run", () => {
    expect(summary.sold).toBeCloseTo(281.25, 4);
    expect(summary.fees0).toBeCloseTo(10944489.7781608, 3);
    expect(summary.escrow0).toBeCloseTo(474864.241075091, 3);
    expect(summary.deposit).toBeCloseTo(2258437.5, 3);
    expect(summary.npv).toBeCloseTo(4693710.767263476, 2);
    expect(summary.nominal).toBeCloseTo(6471735.046905514, 2);
    expect(summary.equityNeed).toBeCloseTo(10912643.832201524, 3);
    expect(summary.back).toBeCloseTo(11053934.675942408, 3);
    expect(summary.cashOnCash).toBeCloseTo(0.012947443892923252, 6);
    expect(summary.flywheelCagr).toBeCloseTo(0.08064617684151454, 6);
    expect(summary.minCash).toBeCloseTo(12899728.343740884, 2);
    expect(summary.emi).toBe(0);
    expect(summary.dedicated).toBe(0);
    expect(summary.sellable).toBe(250);
    expect(Number.isNaN(summary.dscr)).toBe(true);
  });

  it("year-0 row matches the Python run", () => {
    const row0 = rows[0];
    expect(row0.mkt).toBeCloseTo(437779.591126432, 3);
    expect(row0.feeCash).toBeCloseTo(10944489.7781608, 3);
    expect(row0.onboarding).toBeCloseTo(109444.897781608, 3);
    expect(row0.pbt).toBeCloseTo(-437779.591126432, 3);
    expect(row0.operatingCashFlow).toBeCloseTo(10616155.084815975, 3);
    expect(row0.investingCashFlow).toBeCloseTo(-10474864.241075091, 3);
    expect(row0.financingCashFlow).toBeCloseTo(12758437.5, 3);
    expect(row0.cash).toBeCloseTo(12899728.343740884, 2);
    expect(row0.balanceCheck).toBeCloseTo(0, 3);
  });

  it("year-1 row matches the Python run", () => {
    const row1 = rows[1];
    expect(row1.host).toBeCloseTo(2258437.5, 3);
    expect(row1.credits).toBeCloseTo(1853971.875, 3);
    expect(row1.om).toBeCloseTo(162500.0, 3);
    expect(row1.plat).toBeCloseTo(75000.0, 3);
    expect(row1.amortization).toBeCloseTo(705271.3623244877, 3);
    expect(row1.ebitda).toBeCloseTo(166965.625, 3);
    expect(row1.depreciation).toBeCloseTo(666666.6666666666, 3);
    expect(row1.pbt).toBeCloseTo(205570.3206578208, 3);
    expect(row1.tax).toBeCloseTo(51392.5801644552, 3);
    expect(row1.pat).toBeCloseTo(154177.7404933656, 3);
    expect(row1.operatingCashFlow).toBeCloseTo(115573.0448355448, 3);
    expect(row1.balanceCheck).toBeCloseTo(0, 3);
  });

  it("year-2 and year-15 balance checks are ~0 (assets = liabilities + equity)", () => {
    expect(Math.abs(rows[2].balanceCheck)).toBeLessThan(1e-3);
    expect(Math.abs(rows[15].balanceCheck)).toBeLessThan(1e-3);
    expect(rows[15].escrow).toBeCloseTo(0, 6);
    expect(rows[15].cash).toBeCloseTo(16971735.046905514, 1);
  });

  it("balance check is ~0 for every year in the model", () => {
    for (const row of rows) {
      expect(Math.abs(row.balanceCheck)).toBeLessThan(1e-2);
    }
  });

  it("per-plan pricing matches the Python run", () => {
    const byName = Object.fromEntries(plans.map((p) => [p.name, p]));
    expect(byName["Growth-15"].fee).toBeCloseTo(41363.73892216446, 4);
    expect(byName["Growth-15"].kwSold).toBeCloseTo(140.625, 4);
    expect(byName["Growth-15"].realizedXirrPct).toBeCloseTo(11.3205809331414, 4);

    expect(byName["Flexi-10"].fee).toBeCloseTo(38657.68115557856, 4);
    expect(byName["Flexi-10"].kwSold).toBeCloseTo(70.3125, 4);

    expect(byName["Short-3"].fee).toBeCloseTo(25178.363636363632, 4);
    expect(byName["Short-3"].kwSold).toBeCloseTo(42.1875, 4);
    expect(byName["Short-3"].saleYears).toEqual([0, 3, 6, 9, 12]);

    expect(byName["Assured-15"].fee).toBeCloseTo(47906.97138029202, 3);
    expect(byName["Assured-15"].kwSold).toBeCloseTo(28.125, 4);
    expect(byName["Assured-15"].escrowSeed).toBeCloseTo(16884.061904892125, 3);
    expect(byName["Assured-15"].refundFraction).toBeCloseTo(1.0, 6);
  });
});

describe("runModel — debt scenario (50% LTV), regression vs. Python source", () => {
  const debtAssumptions: RunModelAssumptions = { ...DEF_ASSUMPTIONS, financingType: "debt", ltvPct: 0.5 };
  const { rows, summary } = runModel(debtAssumptions, DEF_PLANS);

  it("summary matches the Python debt run", () => {
    expect(summary.financed).toBeCloseTo(5000000, 3);
    expect(summary.emi).toBeCloseTo(813726.9744125576, 3);
    expect(summary.dedicated).toBeCloseTo(100.6620658002236, 3);
    expect(summary.sellable).toBeCloseTo(149.33793419977638, 3);
    expect(summary.dscr).toBeCloseTo(1.1175197154785836, 4);
    expect(summary.npv).toBeCloseTo(5034660.700595549, 1);
    expect(summary.equityNeed).toBeCloseTo(5545169.37824457, 2);
    expect(summary.cashOnCash).toBeCloseTo(0.19078185475163784, 5);
  });

  it("year-1 row matches the Python debt run", () => {
    const row1 = rows[1];
    expect(row1.interest).toBeCloseTo(500000.0, 3);
    expect(row1.principal).toBeCloseTo(313726.97441255755, 3);
    expect(row1.debt).toBeCloseTo(4686273.025587442, 2);
    expect(row1.pat).toBeCloseTo(126069.44026844503, 3);
    expect(row1.balanceCheck).toBeCloseTo(0, 3);
  });

  it("balance check is ~0 for every year", () => {
    for (const row of rows) expect(Math.abs(row.balanceCheck)).toBeLessThan(1e-2);
  });
});

describe("runModel — profit-share diminishing scenario (40% LTV), regression vs. Python source", () => {
  const psAssumptions: RunModelAssumptions = {
    ...DEF_ASSUMPTIONS,
    financingType: "profitshare",
    ltvPct: 0.4,
    profitShareDiminishing: true,
  };
  const { rows, summary } = runModel(psAssumptions, DEF_PLANS);

  it("summary matches the Python profit-share run", () => {
    expect(summary.financed).toBeCloseTo(4000000, 3);
    expect(summary.profitShareRatio).toBeCloseTo(0.4, 6);
    expect(summary.financerFraction).toBeCloseTo(0.16000000000000003, 6);
    expect(summary.ourHostFraction).toBeCloseTo(0.84, 6);
    expect(summary.profitShareBuyoutYears).toBe(7);
    expect(summary.profitSharePeakObligation).toBeCloseTo(932778.5714285716, 2);
    expect(summary.profitSharePayYear1).toBeCloseTo(88291.37921091456, 3);
    expect(summary.profitSharePayTotal).toBeCloseTo(348919.99579947256, 2);
    expect(summary.profitShareBuybackTotal).toBeCloseTo(4000000.0000000005, 2);
    expect(summary.profitShareImpliedRate).toBeCloseTo(0.022072844802728638, 6);
    expect(summary.dscr).toBeCloseTo(1.1175197154785834, 4);
  });

  it("year-1 row matches the Python profit-share run", () => {
    const row1 = rows[1];
    expect(row1.profitSharePay).toBeCloseTo(88291.37921091456, 3);
    expect(row1.profitShareBuyback).toBeCloseTo(571428.5714285715, 3);
    expect(row1.debt).toBeCloseTo(3428571.4285714286, 2);
    expect(row1.pat).toBeCloseTo(463529.74085730134, 2);
    expect(row1.balanceCheck).toBeCloseTo(0, 3);
  });

  it("balance check is ~0 for every year", () => {
    for (const row of rows) expect(Math.abs(row.balanceCheck)).toBeLessThan(1e-2);
  });
});
